#!/bin/bash

# Show Full Path in Bash Prompt
#export PS1='\u@\h \W \$ '
#PS1="\[\033[38m\]\u@\h\[\033[32m\] \w \[\033[31m\]\$(prompt_git)\[\033[37m\]$\[\033[00m\] "

# Set ls behavior
if [[ $OSTYPE == darwin* ]]; then
	alias ls='/bin/ls -alhG'
else
	alias ls='/bin/ls -alh --color'
fi

# Source bash-powerline
source ~/.dotfiles/bash-powerline.sh
#echo $PS1
export PS1="\u\h $(echo $PS1)"
#echo $PS1

# alias common git commands to shorthand
if [ -x "$(command -v git)" ]; then
	alias status='git status'
  alias push='git push'
fi

# youtube-dl shorthand function that does auto retry
if [ -x "$(command -v youtube-dl)" ]; then
	ytdl () { while ! youtube-dl "$1" -c --socket-timeout 5; do echo DISCONNECTED; sleep 5; done; }
fi

