#!/bin/bash

# Source bash-powerline
#if [ -f ~/.dotfiles/opt/bash-powerline.sh ]; then
#  . ~/.dotfiles/opt/bash-powerline.sh
#fi

# Source prompt functions
if [ -f ~/.dotfiles/_promptfunctions ];then
	. ~/.dotfiles/_promptfunctions
fi

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
	debian_chroot=$(cat /etc/debian_chroot)
fi

#
# CREATE THE PROMPT
#

# TITLE:
# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac


if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\] '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w '
fi
unset color_prompt force_color_prompt

# GIT PROMPT
PS1+="[$(git_prompt)] "

# END OF LINE: Add Prompt Symbol
PS1+="$BG_BASE01$FG_BASE2 $PS_SYMBOL $RESET "
