# Powershell: Define history file path
$historyFilePath=(Get-PSReadLineOption).HistorySavePath

# Powershell: Disable Persistent History Saving
#Set-PSReadLineOption -HistorySavePath ""
Set-PSReadLineOption -HistorySaveStyle "SaveAtExit"

# Powershell: Delete history files
Remove-Item -Path "$historyFilePath" -ErrorAction Ignore
# Delete files in PSReadLine history directory
Remove-Item "$env:USERPROFILE\AppData\Roaming\Microsoft\Windows\PowerShell\PSReadLine\*" -Force -ErrorAction SilentlyContinue

# Powershell: Set History count
Set-PSReadLineOption -MaximumHistoryCount 30 # Keep temporary session history

# LESS: Remove history files
Remove-Item -Path "$HOME/.lesshst" -ErrorAction Ignore
Remove-Item -Path "$HOME/_lesshst" -ErrorAction Ignore
$env:LESSHISTFILE = "";

# NODE: Remove history files
Remove-Item -Path "$HOME/.node_repl_history" -ErrorAction Ignore

# OpenSSL/PGP: Remove .rnd (seed generated by OpenSSL/PGP)
Remove-Item -Path "$HOME/.rnd" -ErrorAction Ignore

# VIM: Remove history
Remove-Item -Path "$HOME/.viminfo" -ErrorAction Ignore
Remove-Item -Path "$HOME/.vim/.netrwhist" -ErrorAction Ignore

#SQLite: Remove history
Remove-Item -Path "$HOME/.sqlite_history" -ErrorAction Ignore

#Python: Remove history
Remove-Item -Path "$HOME/.python_history" -ErrorAction Ignore
