#!/bin/bash

foldertotal() {
#Function to calculate total of directory of receipts
# eg. "2019-01-01 Amazon - Books - $104.51"
#         +
#     "2019-01-01 Bestbuy - Movies - $50.13"
local location="$1"
if [ -z "$location" ]; then location="$PWD";fi
echo "Calculating totals for: $location"

array=()
while IFS=  read -r -d $'\0'; do
  filename=$(echo "$REPLY" | xargs -0 basename)
  filenameNoExt="${filename%.*}"

  if [[ $filenameNoExt == *'$'* ]];then
    dollaramtregex='-?\$[0-9]+[.]?[0-9]+'
    if [[ $filenameNoExt =~ $dollaramtregex ]] ;then
      if contains "$RUNNINGSHELL" "zsh"; then
        array+=("${MATCH//$/}")
      else
        array+=("${BASH_REMATCH[0]//$/}")
      fi
    else
      echo "Not amount: $filename"
    fi
  fi
done < <(find "$location" -type f -not -path "*DS_Store*" -print0)

#Ref: https://stackoverflow.com/questions/13635293/unix-shell-script-adding-the-elements-of-an-array-together
dc <<< '[+]sa[z2!>az2!>b]sb'"${array[*]//-/_}lbxp"
}

# youtube-dl shorthand function that does auto retry
if [ -x "$(command -v youtube-dl)" ] &&
   [ -x "$(command -v ffmpeg)" ] &&
   [ -x "$(command -v ffprobe)" ] &&
   [ -x "$(command -v phantomjs)" ]; then
  ytdl () { while ! youtube-dl "$1" -c --socket-timeout 5; do echo DISCONNECTED; sleep 5; done; }
  ytdl-hq () { while ! youtube-dl -f 'bestvideo+bestaudio[ext=m4a]/bestvideo+bestaudio/best' "$1" -c --socket-timeout 5; do echo DISCONNECTED; sleep 5; done; }
  ytdl-mp3 () { while ! youtube-dl --add-metadata --extract-audio --audio-format mp3 -o "%(title)s.%(ext)s" "$1" -c --socket-timeout 5; do echo DISCONNECTED; sleep 5; done; }
else
  ytdl () { youtube-dl "$@" ; }
  ytdl-hq () { youtube-dl "$@" ; }
  ytdl-mp3 () { youtube-dl "$@" ; }

  youtube-dl () {
    install_youtubedl;
    unset -f youtube-dl

    if [ -x "$(command -v youtube-dl)" ]; then
        echo "-- Reloading bash aliases and re-trying your command"
        . "$HOME/.dotfiles/bash/.bash_aliases"; echo ""
        echo "Re-running your original cmd: ${FUNCNAME[${#FUNCNAME[@]}-1]} $*"
        echo ""
        ${FUNCNAME[${#FUNCNAME[@]}-1]} "$@"
    else
        echo "ERROR - Something went wrong in installing youtube-dl, either try again or fix the installer"; echo ""
    fi
  };
fi
