#!/bin/bash

foldertotal() {
#Function to calculate total of directory of receipts
# eg. "2019-01-01 Amazon - Books - $104.51"
#         +
#     "2019-01-01 Bestbuy - Movies - $50.13"
local location="$1"
if [ -z "$location" ]; then location="$PWD";fi
echo "Calculating totals for: $location"

array=()
while IFS=  read -r -d $'\0'; do
  filename=$(echo "$REPLY" | xargs -0 basename)
  filenameNoExt="${filename%.*}"

  if [[ $filenameNoExt == *'$'* ]];then
    dollaramtregex='-?\$[0-9]+[.]?[0-9]+'
    if [[ $filenameNoExt =~ $dollaramtregex ]] ;then
      if contains "$RUNNINGSHELL" "zsh"; then
        array+=("${MATCH//$/}")
      else
        array+=("${BASH_REMATCH[0]//$/}")
      fi
    else
      echo "Not amount: $filename"
    fi
  fi
done < <(find "$location" -type f -not -path "*DS_Store*" -print0)

#Ref: https://stackoverflow.com/questions/13635293/unix-shell-script-adding-the-elements-of-an-array-together
dc <<< '[+]sa[z2!>az2!>b]sb'"${array[*]//-/_}lbxp"
}

# Deprecated in favor of yt-dlp
# # youtube-dl shorthand function that does auto retry
# if [ -x "$(command -v youtube-dl)" ] &&
#    [ -x "$(command -v ffmpeg)" ] &&
#    [ -x "$(command -v ffprobe)" ] &&
#    [ -x "$(command -v phantomjs)" ]; then
#   ytdl () { while ! youtube-dl "$1" -c --socket-timeout 5; do echo DISCONNECTED; sleep 5; done; }
#   ytdl-hq () { while ! youtube-dl -f 'bestvideo+bestaudio[ext=m4a]/bestvideo+bestaudio/best' "$1" -c --socket-timeout 5; do echo DISCONNECTED; sleep 5; done; }
#   ytdl-mp3 () { while ! youtube-dl --add-metadata --extract-audio --audio-format mp3 -o "%(title)s.%(ext)s" "$1" -c --socket-timeout 5; do echo DISCONNECTED; sleep 5; done; }
# else
#   ytdl () { youtube-dl "$@" ; }
#   ytdl-hq () { youtube-dl "$@" ; }
#   ytdl-mp3 () { youtube-dl "$@" ; }

#   youtube-dl () {
#     install_youtubedl;
#     unset -f youtube-dl

#     if [ -x "$(command -v youtube-dl)" ]; then
#         echo "-- Reloading functions and re-trying your command"
#         . "$HOME/.dotfiles/posixshells/modernshell_functions"; echo ""
#         echo "Re-running your original cmd: ${FUNCNAME[${#FUNCNAME[@]}-1]} $*"
#         echo ""
#         ${FUNCNAME[${#FUNCNAME[@]}-1]} "$@"
#     else
#         echo "ERROR - Something went wrong in installing youtube-dl, either try again or fix the installer"; echo ""
#     fi
#   };
# fi

# youtube-dl shorthand function that does auto retry
if [ -x "$(command -v yt-dlp)" ] &&
   [ -x "$(command -v ffmpeg)" ] &&
   [ -x "$(command -v ffprobe)" ] &&
   [ -x "$(command -v phantomjs)" ]; then
  __ytdlSponsersExcludeVideo="sponsor,selfpromo,interaction,music_offtopic"
  __ytdlSponsersExcludeMP3="sponsor,intro,outro,selfpromo,preview,interaction,music_offtopic,poi_highlight"
  ytdl () { ytdl-hq "$@" --compat-options no-live-chat; }
  ytdl-hq () { while ! yt-dlp --embed-subs --compat-options no-live-chat,multistreams --embed-metadata --embed-subs --embed-thumbnail --embed-chapters --remux-video "mkv" --merge-output-format "mkv" -o "%(title)s.%(ext)s" "$1" -c --socket-timeout 5; do echo DISCONNECTED; sleep 5; done; } #--sponsorblock-mark "all" #--sponsorblock-remove "$__ytdlSponsersExcludeVideo"
  ytdl-hq-mp4 () { while ! yt-dlp --embed-subs --compat-options no-live-chat,multistreams --embed-metadata --embed-subs --embed-thumbnail --embed-chapters -f "bv*[ext=mp4][vcodec^=avc]+ba[ext=m4a]/b[ext=mp4] / bv*+ba/b" -o "%(title)s.%(ext)s" "$1" -c --socket-timeout 5; do echo DISCONNECTED; sleep 5; done; }
  ytdl-mp3 () { while ! yt-dlp --embed-metadata --compat-options no-live-chat,multistreams --embed-thumbnail --extract-audio --audio-format "mp3" -o "%(title)s.%(ext)s" "$1" -c --socket-timeout 5; do echo DISCONNECTED; sleep 5; done; } #--sponsorblock-remove "$__ytdlSponsersExcludeMP3"
else
  ytdl () { youtube-dlp "$@" ; }
  ytdl-hq () { youtube-dlp "$@" ; }
  ytdl-mp3 () { youtube-dlp "$@" ; }

  youtube-dlp () {
    __originalCMD=$(caller_func_name 2)
    install_ytdlp;
    unset -f youtube-dlp

    if [ -x "$(command -v yt-dlp)" ]; then
        echo "-- Reloading functions..."
        . "$HOME/.dotfiles/posixshells/modernshell_functions"; echo ""
        echo "Retrying your original command: $__originalCMD $*"
        echo ""
        $__originalCMD "$@"
    else
        echo "ERROR - Something went wrong in installing yt-dlp, either try again or fix the installer"; echo ""
    fi
  };
fi
