#!/bin/bash

foldertotal() {
#Function to calculate total of directory of receipts
# eg. "2019-01-01 Amazon - Books - $104.51"
#         +
#     "2019-01-01 Bestbuy - Movies - $50.13"
local location="$1"
if [ -z "$location" ]; then location="$PWD";fi
echo "Calculating totals for: $location"

array=()
while IFS=  read -r -d $'\0'; do
  filename=$(echo "$REPLY" | xargs -0 basename)
  filenameNoExt="${filename%.*}"

  if [[ $filenameNoExt == *'$'* ]];then
    dollaramtregex='-?\$[0-9]+[.]?[0-9]+'
    if [[ $filenameNoExt =~ $dollaramtregex ]] ;then
      if contains "$RUNNINGSHELL" "zsh"; then
        array+=("${MATCH//$/}")
      else
        array+=("${BASH_REMATCH[0]//$/}")
      fi
    else
      echo "Not amount: $filename"
    fi
  fi
done < <(find "$location" -type f -not -path "*DS_Store*" -print0)

#Ref: https://stackoverflow.com/questions/13635293/unix-shell-script-adding-the-elements-of-an-array-together
dc <<< '[+]sa[z2!>az2!>b]sb'"${array[*]//-/_}lbxp"
}
