#!/bin/bash

# when leaving the console clear the screen to increase privacy
if [ "$SHLVL" = 1 ]; then
    [ -x /usr/bin/clear_console ] && /usr/bin/clear_console -q
fi

history -c

rm -f "$HOME/.bash_history" 2> /dev/null
rm -rf "$HOME/.bash_sessions" 2> /dev/null

# LESS: history delete
rm -f "$HOME/.lesshst" 2> /dev/null

# Remove .rnd (seed generated by OpenSSL/PGP)
rm -f "$HOME/.rnd" 2> /dev/null

# VIM: Remove history
rm -f "$HOME/.viminfo" 2> /dev/null
rm -f "$HOME/.vim/.netrwhist" 2> /dev/null

#SQLite: Remove history
rm -f "$HOME/.sqlite_history" 2> /dev/null
