#!/bin/sh

## On `tput` vs RAW TERMINAL color codes
# Raw terminal codes are not as widely portable
# tput will generate approriate code for terminal running
# Raw terminal codes are madness

# tput:
#  sgr0 #Turn off all attributes
#  setaf <value> # Set foreground color
#  setab <value> # Set background color
#  bold/smul/smso # bold/underline etc, see http://linuxcommand.org/lc3_adv_tput.php

#tput'ed sequences
readonly RESET="\[$(tput sgr0)\]"
readonly C_BOLD="\[$(tput bold)\]"

#tput'ed colors - foreground!
readonly C_BLACK="\[$(tput setaf 0)\]"
readonly C_RED="\[$(tput setaf 1)\]"
readonly C_GREEN="\[$(tput setaf 2)\]"
readonly C_YELLOW="\[$(tput setaf 3)\]"
readonly C_BLUE="\[$(tput setaf 4)\]"
readonly C_PURPLE="\[$(tput setaf 5)\]"
readonly C_CYAN="\[$(tput setaf 6)\]"
readonly C_WHITE="\[$(tput setaf 7)\]"

  #"high intensity" colors
readonly C_LBLACK="\[$(tput setaf 8)\]"
readonly C_LRED="\[$(tput setaf 9)\]"
readonly C_LGREEN="\[$(tput setaf 10)\]"
readonly C_LYELLOW="\[$(tput setaf 11)\]"
readonly C_LBLUE="\[$(tput setaf 12)\]"
readonly C_LPURPLE="\[$(tput setaf 13)\]"
readonly C_LCYAN="\[$(tput setaf 14)\]"
readonly C_LWHITE="\[$(tput setaf 15)\]"

readonly C_SUCCESS=$C_GREEN
readonly C_FAILURE=$C_RED

#Prompt Symbols
readonly SYMBOL_GIT_BRANCH='⑂'
readonly SYMBOL_GIT_MODIFIED='*'
readonly SYMBOL_GIT_PUSH='↑'
readonly SYMBOL_GIT_PULL='↓'

# OS specific symbol
if [ -z "$PS_SYMBOL" ]; then
  case "$(uname)" in
    Darwin)   PS_SYMBOL='' && export PS1_DARWIN=true;;
    Linux)    PS_SYMBOL='$';;
    *)        PS_SYMBOL='>';;
  esac
fi